export default {
    MARK_NOTIFACTION_READ_BY_ID:'MARK_NOTIFACTION_READ_BY_ID',
    MARK_NOTIFACTION_READ_ALL:'MARK_NOTIFACTION_READ_ALL',
    NOTIFACTION_DOLOADING_TRUE:'NOTIFACTION_DOLOADING_TRUE',
    NOTIFACTION_DOLOADING_FALSE:'NOTIFACTION_DOLOADING_FALSE',
    NOTIFACTION_LOADING_TRUE:'NOTIFACTION_LOADING_TRUE',
    NOTIFACTION_LOADING_FALSE:'NOTIFACTION_LOADING_FALSE',
    NOTIFACTION_LOADING_FINISH:'NOTIFACTION_LOADING_FINISH',
}