export default {
    MARK_NOTIFACTION_READ_BY_ID:'MARK_NOTIFACTION_READ_BY_ID',
    MARK_NOTIFACTION_READ_ALL:'MARK_NOTIFACTION_READ_ALL',
    NOTIFACTION_DOLOADING_TRUE:'NOTIFACTION_DOLOADING_TRUE',
    NOTIFACTION_DOLOADING_FALSE:'NOTIFACTION_DOLOADING_FALSE',
    NOTIFACTION_LOADING_TRUE:'NOTIFACTION_LOADING_TRUE',
    NOTIFACTION_LOADING_FALSE:'NOTIFACTION_LOADING_FALSE',
    NOTIFACTION_LOADING_FINISH:'NOTIFACTION_LOADING_FINISH',

    START_LOGIN:'START_LOGIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    END_LOGIN:'END_LOGIN',
    LOGOUT:'LOGOUT'
}